# Generated by Django 5.2.8 on 2025-11-24 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_proyek', models.CharField(editable=False, max_length=20, unique=True)),
                ('nama_proyek', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pemilik_grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_tugas', models.CharField(editable=False, max_length=50, unique=True)),
                ('nama_tugas', models.CharField(max_length=200)),
                ('tipe_tugas', models.CharField(choices=[('PROJECT', 'Proyek'), ('BAU', 'Business As Usual'), ('ADHOC', 'Adhoc')], default='PROJECT', max_length=20)),
                ('tanggal_mulai', models.DateField()),
                ('tenggat_waktu', models.DateField()),
                ('progress', models.IntegerField(default=0, help_text='Persentase 0-100')),
                ('status', models.CharField(choices=[('TODO', 'Akan Dikerjakan'), ('IN_PROGRESS', 'Sedang Dikerjakan'), ('REVIEW', 'Dalam Review'), ('DONE', 'Selesai'), ('OVERDUE', 'Terlambat')], default='TODO', max_length=20)),
                ('ditugaskan_ke', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('induk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.tugas')),
                ('pemilik_grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('proyek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.proyek')),
                ('tergantung_pada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='core.tugas')),
            ],
        ),
    ]
