# Generated by Django 5.2.8 on 2025-11-24 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyek',
            options={'verbose_name': 'Proyek', 'verbose_name_plural': 'Proyek'},
        ),
        migrations.AlterModelOptions(
            name='tugas',
            options={'verbose_name': 'Tugas', 'verbose_name_plural': 'Tugas'},
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Group Admin'), ('LEADER', 'Team Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
