# Generated by Django 5.2.8 on 2025-11-26 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_alter_proyek_options_alter_tugas_options_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateBAU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tugas', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('frekuensi', models.CharField(choices=[('WEEKLY', 'Mingguan'), ('MONTHLY', 'Bulanan'), ('QUARTERLY', 'Triwulan'), ('YEARLY', 'Tahunan')], max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('default_pic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pemilik_grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Template BAU',
                'verbose_name_plural': 'Template BAU',
            },
        ),
    ]
