# Generated by Django 5.2.8 on 2025-12-05 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_templatebau'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatebau',
            name='frekuensi',
            field=models.CharField(choices=[('DAILY', 'Harian'), ('WEEKLY', 'Mingguan'), ('MONTHLY', 'Bulanan'), ('QUARTERLY', 'Triwulan'), ('YEARLY', 'Tahunan')], max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Membuat'), ('UPDATE', 'Mengubah'), ('DELETE', 'Menghapus')], max_length=10)),
                ('target_model', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
