# Generated by Django 5.2.8 on 2026-02-09 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_templatebau_frekuensi_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyek',
            options={},
        ),
        migrations.AlterModelOptions(
            name='templatebau',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tugas',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='templatebau',
            name='dibuat_pada',
        ),
        migrations.AddField(
            model_name='proyek',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Berjalan'), ('ON_HOLD', 'Ditunda (On Hold)'), ('DROP', 'Dibatalkan (Drop)'), ('DONE', 'Selesai')], default='RUNNING', max_length=20),
        ),
        migrations.AddField(
            model_name='proyek',
            name='tanggal_mulai_aktual',
            field=models.DateField(blank=True, null=True, verbose_name='Start (Actual)'),
        ),
        migrations.AddField(
            model_name='proyek',
            name='tanggal_selesai_aktual',
            field=models.DateField(blank=True, null=True, verbose_name='End (Actual)'),
        ),
        migrations.AddField(
            model_name='tugas',
            name='pemberi_tugas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tugas',
            name='tanggal_mulai_aktual',
            field=models.DateField(blank=True, null=True, verbose_name='Start (Actual)'),
        ),
        migrations.AddField(
            model_name='tugas',
            name='tanggal_selesai_aktual',
            field=models.DateField(blank=True, null=True, verbose_name='End (Actual)'),
        ),
        migrations.AlterField(
            model_name='proyek',
            name='tanggal_mulai',
            field=models.DateField(verbose_name='Start (Plan)'),
        ),
        migrations.AlterField(
            model_name='proyek',
            name='tanggal_selesai',
            field=models.DateField(verbose_name='End (Plan)'),
        ),
        migrations.AlterField(
            model_name='templatebau',
            name='frekuensi',
            field=models.CharField(choices=[('WEEKLY', 'Mingguan'), ('MONTHLY', 'Bulanan'), ('QUARTERLY', 'Triwulan'), ('YEARLY', 'Tahunan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('TODO', 'Akan Dikerjakan'), ('IN_PROGRESS', 'Sedang Dikerjakan'), ('REVIEW', 'Dalam Review'), ('DONE', 'Selesai'), ('OVERDUE', 'Terlambat'), ('ON_HOLD', 'Ditunda'), ('DROP', 'Dibatalkan')], default='TODO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='tanggal_mulai',
            field=models.DateField(verbose_name='Start (Plan)'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='tenggat_waktu',
            field=models.DateField(verbose_name='End (Plan)'),
        ),
    ]
