# Generated by Django 5.2.8 on 2026-02-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_proyek_options_alter_templatebau_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='pemberi_tugas',
            field=models.CharField(blank=True, help_text='Bisa nama user sistem atau nama manual (misal: Direktur)', max_length=150, null=True),
        ),
    ]
